Alejandro_Aguilera/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('app_ventas.urls')),
    path('admin', admin.site.urls),
]+static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

app_ventas/urls.py
from django.urls import path


from . import views

app_name = 'app_ventas'

urlpatterns = [
 path('', views.login, name='login'),	
 path('cerrar_sesion', views.cerrar_sesion, name='cerrar_sesion'),	
 path('inicio', views.inicio, name='inicio'),
 path('vista/registrar_pedido', views.registrar_pedido, name='registrar_pedido'),	
 path('vista/aprobacion_pedidos', views.aprobacion_pedidos, name='aprobacion_pedidos'),	
 path('vista/registrar_vendedor', views.registrar_vendedor, name='registrar_vendedor'),	
 path('vista/registrar_cliente', views.registrar_cliente, name='registrar_cliente'),	

 #Reportes
 path('PDF_PedidosA/<int:id>/', views.PDF_PedidosA, name='PDF_PedidosA'),	
 path('PDF_Pedidos/Vendedor/<int:empleado>/', views.PDF_PedidosVendedor, name='PDF_PedidosVendedor'),
#vista de grafica
 path('vista/vista_grafica', views.vista_grafica, name='vista_grafica'),
 path('Apiproductos', views.Apiproductos.as_view(), name='Apiproductos'),
]

app_ventas/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.base import ModelStateFieldsCacheDescriptor
# Create your models here.

class Estado(models.Model):
    descripcion_estado = models.CharField(max_length=20, null = False,blank=False)
    
    def __str__(self):
        return "{}-{}".format(self.pk,self.descripcion_estado)

class Vendedor(models.Model):
    nombres = models.CharField(max_length=100, null = False,blank=False)
    apellidos = models.CharField(max_length=100, null = False,blank=False)
    fecha_registro = models.DateField(auto_now_add=True)
    direccion= models.CharField( max_length=100)
    correo = models.CharField(max_length=50)
    telefono = models.CharField( max_length=50)
    usuario = models.ForeignKey(User,on_delete=models.CASCADE, null=False,blank=False)
    cargo = models.CharField(max_length=100, null = False,blank=False)
    

    def __str__(self):
        return "{}-{}-{}".format(self.pk,self.nombres,self.apellidos,self.cargo)

class Cliente(models.Model):
    nombres = models.CharField(max_length=100, null = False,blank=False)
    apellidos = models.CharField(max_length=100, null = False,blank=False)
    fecha_registro = models.DateField(auto_now_add=True)
    direccion= models.CharField( max_length=100)
    telefono = models.CharField( max_length=50)
    fecha_registro = models.DateField( auto_now_add=True)


    def __str__(self):
        return "{}-{}-{}".format(self.pk,self.nombres,self.apellidos)

class Productos(models.Model):
    nombre_producto = models.CharField(max_length=100, null = False,blank=False)
    descripcion = models.CharField(max_length=200, null = False,blank=False)
    cantidad = models.IntegerField()
    precio = models.DecimalField( max_digits=20, decimal_places=2)
    fecha_registro = models.DateField( auto_now_add=True)

    def __str__(self):
        return "{}-{}-{}".format(self.pk,self.nombre_producto,self.precio)

class Pedido(models.Model):
    producto = models.ForeignKey(Productos,on_delete=models.CASCADE, null=False,blank=False)
    cliente = models.ForeignKey(Cliente,on_delete=models.CASCADE, null=False,blank=False)
    vendedor = models.CharField( max_length=50)
    estado = models.ForeignKey(Estado,on_delete=models.CASCADE, null=False,blank=False)
    cantidad = models.IntegerField()
    fecha_pedido = models.DateField( auto_now_add=True)
    isv = models.DecimalField( max_digits=20, decimal_places=2)
    subtotal = models.DecimalField( max_digits=20, decimal_places=2)
    total = models.DecimalField( max_digits=20, decimal_places=2)
    

    def __str__(self):
        return "{}-{}-{}-{}-{}".format(self.pk,self.producto.nombre_producto,self.producto.pk,self.cliente.nombres,self.estado)

class Pedidos_Aprobados(models.Model):
    descripcion_pedidos = models.CharField(max_length=100, null = False,blank=False)
    encargado = models.CharField(max_length=100, null = False,blank=False)
    pedido = models.ForeignKey(Pedido,on_delete=models.CASCADE, null=False,blank=False)
    fecha_aprobacion = models.DateField( auto_now_add=True)


    def __str__(self):
        return "{}-{}-{}-{}".format(self.pk,self.descripcion_pedidos,self.Pedido.pk,self.pedido.producto)



####APIS

class Respuesta_Comentario(models.Model):
    descripcion_comentario = models.CharField(max_length=20, null = False,blank=False)
    
    def __str__(self):
        return "{}-{}".format(self.pk,self.descripcion_comentario)


class Comentario(models.Model):
    
    correo = models.CharField(max_length=100, null = False,blank=False)
    descripcion_comentario = models.CharField(max_length=20, null = False,blank=False)
    fecha_limite = models.DateField( auto_now_add=True)
    id_respuesta = models.ForeignKey(Respuesta_Comentario,on_delete=models.CASCADE, null=False,blank=False)
    
    def __str__(self):
        return "{}-{}-{}".format(self.pk, self.correo, self.descripcion_comentario)

class Categoria(models.Model):
    descripcion_categoria = models.CharField(max_length=20, null = False,blank=False)
    
    def __str__(self):
        return "{}-{}".format(self.pk,self.descripcion_categoria)

class Grupo(models.Model):
    descripcion_grupo = models.CharField(max_length=20, null = False,blank=False)
    
    def __str__(self):
        return "{}-{}".format(self.pk,self.descripcion_grupo)


class Producto(models.Model):
    codigo = models.CharField(max_length=100, null = False,blank=False)
    descripcion = models.CharField(max_length=100, null = False,blank=False)
    sub_grupo = models.CharField(max_length=100, null = False,blank=False)
    medida_mayor = models.CharField(max_length=100, null = False,blank=False)
    medida_menor = models.CharField(max_length=100, null = False,blank=False)
    precio_mayoreo = models.CharField(max_length=100, null = False,blank=False)
    precio_detalle = models.CharField(max_length=100, null = False,blank=False)
    equivalencia = models.CharField(max_length=100, null = False,blank=False)
    imagen = models.BinaryField(blank = False, null = False, editable = True)
    id_comentario = models.ForeignKey(Comentario,on_delete=models.CASCADE, null=False,blank=False)
    id_categoria = models.ForeignKey(Categoria,on_delete=models.CASCADE, null=False,blank=False)
    id_grupo = models.ForeignKey(Grupo,on_delete=models.CASCADE, null=False,blank=False)
    
    def __str__(self):
        return "{}-{}-{}-{}-{}-{}-{}".format(self.pk, self.codigo,self.descripcion, self.id_grupo, self.id_comentario, self.id_categoria, self.sub_grupo)

app_ventas/views.py
from django.db.models.expressions import Exists
from django.shortcuts import render,redirect
from django.http import HttpResponseRedirect,JsonResponse, HttpResponse
from django.urls import reverse
from django.db.models import Sum,Q
from django.contrib.auth.hashers import make_password
from datetime import date, datetime
from django.utils import timezone

from app_ventas.models import *
from django.contrib.auth import login as auth_login,logout,authenticate
from django.contrib.auth.decorators import login_required, permission_required
from django.db import transaction,connections
#Correo
from django.core.mail import EmailMessage, send_mail
from Alejandro_Aguilera.settings import EMAIL_HOST_USER
#Librerias para PDF
from xhtml2pdf import pisa
from django.template.loader import get_template
from io import StringIO
from io import BytesIO

#####
import requests
import json
import base64

from rest_framework import serializers
from rest_framework import status
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework.parsers import JSONParser

# Create your views here.

#Pagina principal de inicio

def inicio(request):
    try:
        cant_producto_precio = Productos.objects.all().aggregate(cant_total=Sum('precio'))
        precio_total_productos = cant_producto_precio['cant_total']

        cant_producto = Productos.objects.all().aggregate(totalP=Sum('cantidad'))
        cant_total_productos = cant_producto['totalP']
     
    except Productos.DoesNotExist:
        precio_total_productos = 0.1
        precio_total_productos = 0.1
        
    # consulta_fechas = Pedido.objects.filter(fecha_pedido__range=["2021-11-24", "2021-11-24"])#Consulta por rango de fechas, puee servir xd
    # # rango_precio_productos = Productos.objects.get(Q(precio > 100000)
    # print(consulta_fechas)
    
    ctx = {'precio':precio_total_productos,'totalP':cant_total_productos}
    if request.user.is_authenticated:
        return render(request,'inicio.html',ctx)
    else:
        return render(request,'error.html',ctx)

@login_required
def cerrar_sesion(request):
    logout(request)
    return HttpResponseRedirect(reverse('app_ventas:login'))

#Login
def login(request):
    mensaje=''
    if request.user.is_authenticated:
        return redirect('app_ventas:inicio')

    if request.method == 'POST':
        username = request.POST.get('usuario')
        contrasenia = request.POST.get('contrasenia')
        user = authenticate(username=username,password=contrasenia)
        if user is not None:
            if user.is_active:
                auth_login(request,user)
                return redirect('app_ventas:inicio')
            else:
                mensaje = 'USUARIO INACTIVO'
                return render(request,'login.html',{'mensaje':mensaje})
        else:
            mensaje = 'USUARIO O CONTRASEÑA INCORRECTO'
            return render(request,'login.html',{'mensaje':mensaje})

    return render(request,'login.html')

#Registro para el pedido
@login_required
def registrar_pedido(request):
    if request.user.is_authenticated:
        pedidos = Pedido.objects.all()
        productos = Productos.objects.all()
        clientes = Cliente.objects.all()
        ret_data,query_pedido,errores = {},{},{}

        if request.method == 'POST':
            
            ret_data['producto'] = request.POST.get('producto')
            ret_data['cliente'] = request.POST.get('cliente')
            ret_data['cantidad'] = request.POST.get('cantidad')
            
            # Producto
            if request.POST.get('producto') == '':
                errores['producto'] = "Debe ingresar el producto"

            # elif Productos.objects.filter(pk = int(request.POST.get("producto")).exists(): 
            # 	#Si el registro ya existe en la base de datos
            # 	errores['existe'] = 'ID ya Existente!!'
    
            else:
                query_pedido["producto"] = Productos.objects.get(pk=int(request.POST.get("producto")))

            
            # Ciente
            if request.POST.get('cliente') == '':
                errores['cliente'] = "Debe ingresar el cliente"
                
            else:
                query_pedido["cliente"] = Cliente.objects.get(pk=int(request.POST.get("cliente")))
            
            # Cantidad
            if request.POST.get('cantidad') == '' or request.POST.get('cantidad') == "0":
                errores['cantidad'] = "Debe ingresar la cantidad"
                
            else:
                query_pedido["cantidad"] = request.POST.get("cantidad")
                cantidad = int(request.POST.get("cantidad"))
            
            
            

            if not errores:

                try:
                    
                    query_pedido["vendedor"] = request.user
                    query_pedido["estado"] = Estado.objects.get(pk=1)
                    
                    
                    F_precio = Productos.objects.get(pk=int(request.POST.get("producto")))
                    precio = F_precio.precio
                    query_pedido["subtotal"] = float(cantidad*precio)
                    subtotal = query_pedido["subtotal"]
                    query_pedido["isv"] = float(subtotal*0.15)
                    query_pedido["total"] = float(subtotal) + float(subtotal*0.15)
                    ped = Pedido(**query_pedido)
                    ped.save()


                except Exception as e:
                    transaction.rollback()
                    errores['administrador'] = e
                    print (e)
                    ctx = {'pedidos':pedidos,'errores':errores,'ret_data':ret_data, 'clientes':clientes, 'productos':productos }

                    return render(request,'registrar_pedido.html',ctx)
                else:
                    transaction.commit()
                    return HttpResponseRedirect(reverse('app_ventas:registrar_pedido')+'?ok')
            else:
                ctx = {'pedidos':pedidos,'errores':errores,'ret_data':ret_data, 'clientes':clientes, 'productos':productos}
                return render(request,'registrar_pedido.html',ctx)
        else:
            ctx = {'pedidos':pedidos, 'clientes':clientes, 'productos':productos}
            return render(request,'registrar_pedido.html',ctx)
    else:
        return redirect('app_ventas:inicio')

#Aprobacion de pedidos

def aprobacion_pedidos(request):
    if request.user.is_authenticated:

        if request.user.is_superuser:
            PAprobados = Pedidos_Aprobados.objects.all()
            pedidos = Pedido.objects.exclude(estado = 2) #Realizamos una validacion para excluir y solo mostar los pedidos con estado "Aprobados"

            ret_data,query_pedidosA,errores = {},{},{}

            if request.method == 'POST':
                ret_data['pedido'] = request.POST.get('pedido')
                ret_data['descripcion_pedidos'] = request.POST.get('descripcion_pedidos')
                
                # pedido
                if request.POST.get('pedido') == '':
                    errores['pedido'] = "Debe ingresar el pedido"
                    
                else:
                    query_pedidosA["pedido"] = Pedido.objects.get(pk=int(request.POST.get("pedido")))
                
                #dscripcion
                query_pedidosA["descripcion_pedidos"] = request.POST.get("descripcion_pedidos")
                    

                if not errores:
                    try:
                        
                        query_pedidosA["encargado"] = request.user
                        Papronados = Pedidos_Aprobados(**query_pedidosA)
                        Papronados.save()
                        #Suma del total de productos del pedido
                        cant_producto_pedido = Pedido.objects.filter(pk=int(request.POST.get("pedido"))).aggregate(cant_total=Sum('cantidad'))
                        
                        pro =Pedido.objects.get(pk=int(request.POST.get("pedido")))#btengo un objeto que me peritira anej los diferentes campos del pedido
                        #Suma de la cantida del produco que se eligio para el pedido
                        cant_producto_total = Productos.objects.filter(pk=int(pro.producto.pk)).aggregate(cant_totalP=Sum('cantidad'))
                        #Disminucion de la cantidad de productos que se realizo el pedido y la cantidad restante.
                        resta_productos =int(cant_producto_total['cant_totalP']) -int(cant_producto_pedido['cant_total'])
                        

                        #Restar productos al hacer pedido
                        cantidad_productos = Productos.objects.filter(pk=int(pro.producto.pk)).update(
                                                                                cantidad =  resta_productos
                                                                                )

                        #Cambio de estado
                        nw_estado = Pedido.objects.filter(pk=int(request.POST.get("pedido"))).update(
                                                                                estado =  Estado.objects.get(pk=2)
                                                                                )

                    except Exception as e:
                        transaction.rollback()
                        errores['administrador'] = e
                        ctx = {'pedidos':pedidos,'PAprobados':PAprobados,'errores':errores,'ret_data':ret_data}

                        return render(request,'aprobacion_pedidos.html',ctx)
                    else:
                        transaction.commit()
                        return HttpResponseRedirect(reverse('app_ventas:aprobacion_pedidos'))
                else:
                    ctx = {'pedidos':pedidos,'PAprobados':PAprobados,'errores':errores,'ret_data':ret_data}
                    return render(request,'aprobacion_pedidos.html',ctx)
            else:

app_ventas/templates/PDF_PedidosVendedor.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>Reporte Pedidos Activos</title>
	<link rel="stylesheet" href="">
	<style>
		.td-header{
	      border:none;
	    }

	    td{
	      font-size: 12px;
	      padding-left:0;
	      padding: 3px 0 0 0;
	      border-bottom: 1px solid #8B8B8B;
	    }

	    th{
	    	font-size: 12px;
	    	padding: 4px 0 0 0;
	    	border-bottom: 1px solid #8B8B8B;
	    }

	    .titulo{
	      margin: 0;
	      text-align:center;
	      font-size: 20px;
	    }
	</style>
</head>
<body>
	<div style="width:100%" id="header_content">
		<h1 class="titulo">Reporte ventas mensual</h1>
        <hr>
		<table style="width:70%;">
	      <tr>
	        
	        <td class="td-header" style="width:500px;">
	          <h2 style="text-align:center;">Empresa <b>XYZ</b></h2>
	        </td>
            <td class="td-header"></td>
	        <td class="td-header" style="width:400px;"><h2>Empleado :{{vendedores.nombres}} {{vendedores.apellidos}}</h2> <h2>Cargo : {{vendedores.cargo}}</h2></td>
            
         </tr>
         <tr>
            
            <td class="td-header" style="width:100px; text-align:center;">
	          <img src="https://th.bing.com/th/id/R.61420c958fef22e82419c06c23049a34?rik=lGt4h84LdJjvZQ&riu=http%3a%2f%2fwww.graphis.com%2fmedia%2fuploads%2fcache%2fb3%2fe4%2fb3e4bf424d71554226fc9c8bbe1d9c91.jpg&ehk=dg%2bU7lWY%2b5aG4qqNGBvrUQvvJCKnSHcYhsVpRtpmrtY%3d&risl=&pid=ImgRaw&r=0">
	        </td>
            <td class="td-header"></td>
           <td class="td-header"></td>
         </tr>

	    </table>
	</div>

	<table style="width:100%; margin-top: 10px">
		<thead>
			<tr>
				<th colspan="8" style="text-align:center; border-bottom: 3px solid #8B8B8B; border-top: 1px solid #8B8B8B; font-size:14px;">Detalle </th>
			</tr>
			<tr>
				<th>Cliente</th>
				<th>Fecha pedido</th>
				<th >Direccion</th>
				<th>Telefono</th>
				<th>Estado</th>
				<th>Producto</th>
				<th>Catidad</th>
                <th></th>
				<th>Vendedor</th>
                <th></th>
                
				
			</tr>
            <br>
		</thead>
        
		<tbody>
		
			{% for pedidos in pedidos  %}
				<tr>
					<td style="width:90px; text-align:center;">{{pedidos.cliente.nombres}}-{{pedidos.cliente.apellidos}}  </td> 
					<td style="width:70px; text-align:center;">  {{pedidos.fecha_pedido}}</td>
                    <td style="width:70px; text-align:center;">  {{pedidos.cliente.direccion}}</td>
                    <td style="width:70px; text-align:center;">{{pedidos.cliente.telefono}}</td>
					<td style="width:70px; text-align:center;">{{pedidos.estado}}</td>
					<td style="width:70px; text-align:center;">{{pedidos.producto}}</td>
					<td style="width:70px; text-align:center;">{{pedidos.cantidad}}</td>
                    <td ></td>
					<td style="width:70px; text-align:center;">{{pedidos.vendedor}}</td>
                    <td ></td>
					
				</tr>
            {% endfor %}
                
				
	

		

		
		</tbody>
	</table>
</body>
</html>

app_ventas/templates/registrar_vendedor.html
{% extends "principal_base.html" %}
{% block titulo %}
Pedidos | Registro Vendedor
{% endblock titulo %}
{% load static %}
{% block content %}

<div id="layoutAuthentication">
  <div id="layoutAuthentication_content">
      <main>
          <div class="container">
              <div class="row justify-content-center">
                  <div class="col-lg-20">
                      <div class="card shadow-lg border-0 rounded-lg mt-5 ">
                          <div class="card-header  bg-secondary"><h3 class="text-center font-weight-light text-white">Registro Empleados</h3></div>
                          <div class="card-body">
                            <form class="needs-validation"  action="{% url 'app_ventas:registrar_vendedor' %}" method="POST" novalidate>
                              {% csrf_token %}

                              <div class="row">
                                    <div class="col-md-4 mb-3">
                                        <label for="validationCustom02">Nombres</label>
                                        <input type="text" class="form-control" id="validationCustom02" placeholder="Nombres" value="" name="nombres" onkeypress="return sololetras(event)" required>
                                        <div class="valid-feedback">
                                            Looks good!
                                        </div>
                                        {% if errores.nombres %}
                                            <div class="alert alert-danger alert-dismissible " role="alert">
                                                <strong>ERROR! </strong>{{errores.nombres}}
                                            </div>
                                        {% endif %}
                                    </div>

                                    <div class="col-md-4 mb-3">
                                        <label for="validationCustom02">Apellidos</label>
                                        <input type="text" class="form-control" id="validationCustom02" placeholder="Apellidos" value="" name="apellidos" onkeypress="return sololetras(event)" required>
                                        <div class="valid-feedback">
                                            Looks good!
                                        </div>
                                        {% if errores.apellidos %}
                                            <div class="alert alert-danger alert-dismissible " role="alert">
                                                <strong>ERROR! </strong>{{errores.apellidos}}
                                            </div>
                                        {% endif %}
                                    </div>

                                    <div class="col-md-4 mb-3">
                                        <label for="validationCustom02">Direccion</label>
                                        <input type="text" class="form-control" id="validationCustom02" placeholder="Direccion" value="" name="direccion" required>
                                        <div class="valid-feedback">
                                            Looks good!
                                        </div>
                                        {% if errores.direccion %}
                                            <div class="alert alert-danger alert-dismissible " role="alert">
                                                <strong>ERROR! </strong>{{errores.direccion}}
                                            </div>
                                        {% endif %}
                                    </div>
                              </div>

                              <div class="row">
                                    <div class="col-md-4 mb-3">
                                        <label for="validationCustom02">Correo</label>
                                        <input type="text" class="form-control" id="validationCustom02" placeholder="Correo" value="" name="correo" required>
                                        <div class="valid-feedback">
                                            Looks good!
                                        </div>
                                        {% if errores.correo %}
                                            <div class="alert alert-danger alert-dismissible " role="alert">
                                                <strong>ERROR! </strong>{{errores.correo}}
                                            </div>
                                        {% endif %}
                                    </div>
                                    <div class="col-md-4 mb-3">
                                        <label for="validationCustom02">Telefono</label>
                                        <input type="text" class="form-control" id="validationCustom02" placeholder="Telefono" value="" name="telefono" onkeypress="return soloNumeros(event)" required>
                                        <div class="valid-feedback">
                                            Looks good!
                                        </div>
                                        {% if errores.telefono %}
                                            <div class="alert alert-danger alert-dismissible " role="alert">
                                                <strong>ERROR! </strong>{{errores.telefono}}
                                            </div>
                                        {% endif %}
                                    </div>
                                    <div class="col-md-4 mb-3">
                                        <label for="validationCustom02">Cargo</label>
                                        <input type="text" class="form-control" id="validationCustom02" placeholder="Cargo" value="" name="cargo" onkeypress="return sololetras(event)" required>
                                        <div class="valid-feedback">
                                            Looks good!
                                        </div>
                                        {% if errores.cargo %}
                                            <div class="alert alert-danger alert-dismissible " role="alert">
                                                <strong>ERROR! </strong>{{errores.cargo}}
                                            </div>
                                        {% endif %}
                                    </div>
                              </div
                               
                              <br>
                              <div col-md2>
                              <button class="btn btn-primary btn-sm" type="submit" >Guardar</button>
                            </div> 
                            </form>
                            
                            
                          </div>
                          
                      </div>
                  </div>
              </div>
          </div>
      </main>
<br>
      <div class="card mb-4">
        <div class="card-header bg-secondary text-white">
            <i class="fas fa-table me-1"></i>
            Tabla Empleados
        </div>
        <div class="card-body">
            <table id="datatablesSimple" class="table table-striped">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Nombre del Vendedor</th>
                        <th>Direccion</th>
                        <th>Correo</th>
                        <th>Telefono</th>
                        <th>Usuario</th>
                        <th>Cargo</th>
                        <th>Fecho de ingreso</th>
                        <th> PDF</th>
                        

                    </tr>
                </thead>
                
                <tbody>
                   
                      
                      {% for vendedor in vendedores %}
                        <tr>
                            <td>{{vendedor.pk}}</td>
                            <td>{{vendedor.nombres}} {{vendedor.apellidos}} </td>
                            <td>{{vendedor.direccion}}</td>
                            <td>{{vendedor.correo}}</td>
                            <td>{{vendedor.telefono}}</td>
                            <td>{{vendedor.usuario.username}}</td>
                            <td>{{vendedor.cargo}}</td>
                            <td>{{vendedor.fecha_registro}}</td>
                            <td>
                              <center>
                               <a href="{% url 'app_ventas:PDF_PedidosVendedor' vendedor.usuario.pk %}" class="btn btn-outline-danger btn-sm" role="button" aria-pressed="true" target="_blank data-toggle="tooltip" data-placement="left" title="Generar PDF""><b>PDF</b></a>
                              </center>
                            </td>
                         </tr>
                      {% empty %}
                        No hay registros...
                      {% endfor %}
                    
                    
                    
                </tbody>
            </table>
        </div>
    </div>
  </div>
  
  

    

{% endblock content %}

{% block js %}


<script>

$(document).ready(function()
    {
        $('#datatablesSimple').dataTable( {
            "language": {
                "url": "//cdn.datatables.net/plug-ins/1.10.16/i18n/Spanish.json"
            },
            dom: 'Bfrtip',
            buttons: [
                'copy', 'csv', 'excel', 'pdf', 'print'
            ]
        } );
    } 
);

  // Example starter JavaScript for disabling form submissions if there are invalid fields
  (function() {
    'use strict';
    window.addEventListener('load', function() {
      // Fetch all the forms we want to apply custom Bootstrap validation styles to
      var forms = document.getElementsByClassName('needs-validation');
      // Loop over them and prevent submission
      var validation = Array.prototype.filter.call(forms, function(form) {
        form.addEventListener('submit', function(event) {
          if (form.checkValidity() === false) {
            event.preventDefault();
            event.stopPropagation();
          }
          form.classList.add('was-validated');
        }, false);
      });
    }, false);
  })();

  function soloNumeros(e)
{
    var key = e.keycode || e.which;
    var tecla = String.fromCharCode(key).toLowerCase();
    numeros = ".0123456789";
    especiales = [44, 45, 46];
    tecla_especial = false;

    for(var i in especiales)
    {
        if(key == especiales)
        {
            tecla_especial = true;
            break;
        }
    }

    if(numeros.indexOf(tecla) == -1 && !tecla_especial)
    {

        return false;
    }

}


function sololetras(e)
{
    var key = e.keycode || e.which;
    var tecla = String.fromCharCode(key).toLowerCase();
    numeros = "qwertyuiopasdfghñjklzxcvbnmQWERTYUIOPASDFGHJKLZXCVBNMÑ ";
    especiales = [44, 45, 46];
    tecla_especial = false;

    for(var i in especiales)
    {
        if(key == especiales)
        {
            tecla_especial = true;
            break;
        }
    }

    if(numeros.indexOf(tecla) == -1 && !tecla_especial)
    {

        return false;
    }

}



  </script>
{% endblock js %}